<a href="https://colab.research.google.com/github/JuanBarcelon/Linear_Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_4_Barcelon_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Laboratory 6: Matrix Operations

Objectives:
1. Be familiar with the fundamental matrix operations.
2. Apply the operation to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

#Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#Transposition

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$A^T = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

This can now be achieved programmatically by using np.transpose() or using the T method.


In [ ]:
Mat1 = np.array([
    [5 ,3, 5],
    [1, -6, 6],
    [7, -2, 4]
])
Mat1

array([[ 5,  3,  5],
       [ 1, -6,  6],
       [ 7, -2,  4]])

In [ ]:
## To Transpose the matrix..
Matv2 = np.transpose(Mat1)
Matv2

array([[ 5,  1,  7],
       [ 3, -6, -2],
       [ 5,  6,  4]])

In [ ]:
## Another way to transpose a matrix
MatT = Mat1.T
MatT

array([[ 5,  1,  7],
       [ 3, -6, -2],
       [ 5,  6,  4]])

In [ ]:
## To check if the elements of the 2 matrices are equal
np.array_equiv(Matv2, MatT) 


True

In [ ]:
B = np.array([
    [1,2,3,4,5,6,7,8,9,0,1,2],
    [1,0,2,1,0,2,1,0,2,1,0,2],
])
B.shape

(2, 12)

In [ ]:
np.transpose(B).shape

(12, 2)

In [ ]:
B.T.shape

(12, 2)

## Try to create your own matrix(you can try non-squares) to test transposition

In [ ]:
## Try out your code here.
NB=np.array([
      [2,5,4,5,1,7],
      [3,1,6,6,7,6],
      [3,3,2,2,1,1]
])
NB.shape

(3, 6)

In [ ]:
np.transpose(NB).shape

(6, 3)

In [ ]:
NB.T.shape

(6, 3)

In [ ]:
A_B = NB.T
A_B

array([[2, 3, 3],
       [5, 1, 3],
       [4, 6, 2],
       [5, 6, 2],
       [1, 7, 1],
       [7, 6, 1]])

#Dot Product / Inner Product
If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$
 
This could be achieved programmatically using np.dot(), np.matmul() or the @ operator.

In [ ]:
yo = np.array([
    [3,3,1],
    [0,1,3],
    [3,2,2]
])
wow = np.array([
    [-2,4,6],
    [8,6,4],
    [2,3,1]
])


In [ ]:
np.array_equiv(yo, wow)

False

In [ ]:
np.dot(yo,wow)

array([[20, 33, 31],
       [14, 15,  7],
       [14, 30, 28]])

In [ ]:
yo.dot(wow)

array([[20, 33, 31],
       [14, 15,  7],
       [14, 30, 28]])

In [ ]:
yo @ wow

array([[20, 33, 31],
       [14, 15,  7],
       [14, 30, 28]])

In [ ]:
np.matmul(yo,wow)

array([[20, 33, 31],
       [14, 15,  7],
       [14, 30, 28]])

## Rule 1: The inner dimensions of the two matrices in question must be the same.

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:


$$A = \begin{bmatrix}2 &4\\ 5 & {-2} \\0 & 1 \end{bmatrix}, B = \begin{bmatrix}1 & 1\\3 & 3 \\{-1} & {-2} \end{bmatrix}, C = \begin{bmatrix}0 & 1 & 1\\ 1 & 1& 2\end{bmatrix}$$


So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
M1 = np.array([
    [4, 2],
    [3, -4],
    [1, 3],
    [3,1]
])
M2 = np.array([
    [3,2],
    [4,4],
    [-5,-2],
    [2,3]
])
M3 = np.array([
    [0,1,1],
    [1,1,2]
])
print(M1.shape)
print(M2.shape)
print(M3.shape)

(4, 2)
(4, 2)
(2, 3)


In [ ]:
M1 @ M3

array([[ 2,  6,  8],
       [-4, -1, -5],
       [ 3,  4,  7],
       [ 1,  4,  5]])

In [ ]:
M2 @ M3

array([[ 2,  5,  7],
       [ 4,  8, 12],
       [-2, -7, -9],
       [ 3,  5,  8]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix  with a shape of  and matrix  with a shape of ,  should have a shape .

In [ ]:
M1 @ M2.T

array([[ 16,  24, -24,  14],
       [  1,  -4,  -7,  -6],
       [  9,  16, -11,  11],
       [ 11,  16, -17,   9]])

In [ ]:
AB = np.array([
    [1,3,4,2,4],
    [3,3,4,4,5]
])
CD = np.array([
    [1,1,2,3,4],
    [1,1,2,2,3]
])
print(AB.shape)
print(CD.shape)

(2, 5)
(2, 5)


In [ ]:
CD.T @ AB

array([[ 4,  6,  8,  6,  9],
       [ 4,  6,  8,  6,  9],
       [ 8, 12, 16, 12, 18],
       [ 9, 15, 20, 14, 22],
       [13, 21, 28, 20, 31]])

In [ ]:
AB @ CD.T

array([[34, 28],
       [46, 37]])

## Rule 2: Dot Product has special properties

1. $A \cdot B \neq B \cdot A$
2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
3. $A\cdot(B+C) = A\cdot B + A\cdot C$
4. $(B+C)\cdot A = B\cdot A + C\cdot A$
5. $A\cdot I = A$
6. $A\cdot \emptyset = \emptyset$

In [ ]:
#Declaration of matrices
A = np.array([
    [5,2,4],
    [1,1,2],
    [1,2,3]
])
B = np.array([
    [2,2,2],
    [3,4,3],
    [5,5,5]
])
C = np.array([
    [2,0,0],
    [9,2,3],
    [8,2,5]
])

In [ ]:
# First property
np.array_equal(A@B, C@A)

False

In [ ]:
# Second property
print(A @ (B @ C))
print((A @ B) @ C)
np.array_equiv(A @ (B @ C), (A @ B) @ C)

[[702 148 294]
 [294  62 123]
 [455  96 190]]
[[702 148 294]
 [294  62 123]
 [455  96 190]]


True

In [ ]:
# Third property 
print(A @ (B + C))
print((A @ B) + (A @ C))
np.array_equiv(A @ (B + C), (A @ B) + (A @ C))

[[96 50 62]
 [42 22 28]
 [67 35 44]]
[[96 50 62]
 [42 22 28]
 [67 35 44]]


True

In [ ]:
# Fourth property
print((B + C) @ A)
print((B @ A) + (C @ A))
np.array_equiv((B + C) @ A, (B @ A) + (C @ A))

[[24 14 26]
 [72 42 78]
 [82 53 96]]
[[24 14 26]
 [72 42 78]
 [82 53 96]]


True

In [ ]:
# Fifth property
print(A@np.eye(3))
np.array_equiv(A, A@np.eye(3))
 

[[5. 2. 4.]
 [1. 1. 2.]
 [1. 2. 3.]]


True

In [ ]:
# sixth property
print(A @ np.zeros((3,3)))
print(np.zeros((3,3)))
np.array_equiv(A @ np.zeros((3,3)),np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

#Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
A = np.array([
    [2,4],
    [1,1]
])

B = np.array([
    [3,5,2],
    [2,4,8],
    [2,3,1]
])
print(np.linalg.det(A))
print(np.linalg.det(B))


-2.0
5.999999999999995


In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

#Inverse
The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
dog = np.array([
    [9,8,1],
    [-2,6,2],
    [5,5,8]
])

np.array(dog @ np.linalg.inv(dog), dtype=int)

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
cat = np.array([
    [2,5],
    [-6,8]
])
mouse=np.linalg.inv(cat)
mouse

array([[ 0.17391304, -0.10869565],
       [ 0.13043478,  0.04347826]])

In [ ]:
cat @ mouse

array([[1., 0.],
       [0., 1.]])

In [ ]:
## And now let's test your skills in solving a matrix with high dimensions:
Big = np.array([
    [9,4,7,2,3,4,4],
    [12,4,5,1,0,0,8],
    [2,4,11,2,5,11,5],
    [1,2,3,4,5,6,7],
    [2,1,18,4,5,2,9],
    [13,2,5,10,4,2,1],
    [7,6,5,4,3,2,1]
])
Big_inv = np.linalg.inv(Big)
np.array(Big @ Big_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [ ]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

In [ ]:
XX= np.array([
              [4,3,4],
              [2,3,1],
              [3,1,4]
])
XXX = np.linalg.inv(XX)
XXX

array([[11., -8., -9.],
       [-5.,  4.,  4.],
       [-7.,  5.,  6.]])

In [ ]:
XX @ XXX

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 8.88178420e-16,  1.00000000e+00,  0.00000000e+00],
       [ 3.55271368e-15, -3.55271368e-15,  1.00000000e+00]])

# Task 1
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than (3,3). In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [22]:
#Declaration of matrices
ADU = np.array([
    [6,12,8,4],
    [2,1,11,2],
    [3,3,3,4],
    [0,0,8,3]
])
UST = np.array([
    [10,11,4,3],
    [3,2,9,9],
    [5,6,7,8],
    [12,8,2,1]
])
FEU = np.array([
    [2,0,9,0],
    [2,11,16,12],
    [8,9,3,4],
    [2,4,9,2]
])

## First property

In [34]:
ADU @ UST

array([[184, 170, 196, 194],
       [102, 106,  98, 105],
       [102,  89,  68,  64],
       [ 76,  72,  62,  67]])

In [35]:
FEU @ ADU

array([[ 39,  51,  43,  44],
       [ 82,  83, 281, 130],
       [ 75, 114, 204,  74],
       [ 47,  55, 103,  58]])

In [36]:
np.array_equal(ADU@UST, FEU@ADU)

False

## Second property

In [37]:
ADU @ (UST @ FEU)

array([[2664, 4410, 6710, 3212],
       [1410, 2468, 3853, 1874],
       [1054, 1847, 3122, 1468],
       [ 926, 1618, 2625, 1246]])

In [39]:
(ADU @ UST) @ FEU

array([[2664, 4410, 6710, 3212],
       [1410, 2468, 3853, 1874],
       [1054, 1847, 3122, 1468],
       [ 926, 1618, 2625, 1246]])

In [40]:
np.array_equiv(ADU @ (UST @ FEU), (ADU @ UST) @ FEU)

True

## Third Property

In [41]:
ADU @ (UST+ FEU)

array([[292, 390, 502, 378],
       [200, 224, 183, 165],
       [146, 165, 188, 120],
       [146, 156, 113, 105]])

In [42]:
(ADU @ UST)+ (ADU @ FEU)

array([[292, 390, 502, 378],
       [200, 224, 183, 165],
       [146, 165, 188, 120],
       [146, 156, 113, 105]])

In [43]:
np.array_equiv(ADU @ (UST+FEU) , ADU @ UST + ADU @ FEU)

True

## Fourth Property

In [44]:
(UST + FEU) @ ADU

array([[133, 194, 280, 131],
       [131, 148, 426, 209],
       [138, 201, 395, 158],
       [141, 213, 301, 133]])

In [60]:
(UST @ ADU) + (FEU @ ADU)

array([[133, 194, 280, 131],
       [131, 148, 426, 209],
       [138, 201, 395, 158],
       [141, 213, 301, 133]])

In [46]:
np.array_equiv((UST + FEU) @ ADU, (UST @ ADU) + (FEU @ ADU))

True

## Fifth property

In [48]:
ADU

array([[ 6, 12,  8,  4],
       [ 2,  1, 11,  2],
       [ 3,  3,  3,  4],
       [ 0,  0,  8,  3]])

In [52]:
ADU @ np.eye(4)

array([[ 6., 12.,  8.,  4.],
       [ 2.,  1., 11.,  2.],
       [ 3.,  3.,  3.,  4.],
       [ 0.,  0.,  8.,  3.]])

In [54]:
np.array_equiv(ADU, ADU@np.eye(4))

True

## Sixth Property

In [55]:
ADU @ np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [56]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
np.array_equiv(ADU @ np.zeros((4,4)),np.zeros((4,4)))

True