<a href="https://colab.research.google.com/github/JuanBarcelon/Linear_Algebra_ChE_2nd-Sem-2021-2022/blob/main/Laboratory_2_Matrices_BARCELON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE

# Assignment 4: Matrices


### Objectives

At the end of this activity you will be able to:
- Be familiar with matrices and their relation to linear equations.
- Perform basic matrix operations.
- Program and translate matrix equations and operations using Python.




# Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline


## Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have  and  as system of equation.

$$
A = \left\{
    \begin{array}\
        10x + 5y \\ 
        3x - 8y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
      w- 2x + 3y - 4z \\
      3w - x - 2y + z \\
      2w = x + 3y - 2z
    \end{array}
  \right. \\
$$

We could see that A is a system of 2 equations with 2 parameters. While B is a system of 3 equations with 3 parameters. B is a system of 4 equations with 4 parameters. We can represent them as matrices as:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & -10\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix}\\
$$


## Declaring Matrixes

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using shape, dimensions and size attributes, we'll use them to analyze these matrices.


In [8]:
## Since we'll keep on describing matrices. Let's make a function.

def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')


In [9]:
## Declaring a 2 x 2 matrix
Mat_A = np.array([
              [5,10],
              [15,20]
])
describe_mat(Mat_A)



Matrix:
[[ 5 10]
 [15 20]]

Shape:	(2, 2)
Rank:	2



# Categorizing matrices

There are several ways of classifying matrices. Once could be according to their shape and another is according to their element values. We'll try to go through them.

## According to shape

### row and column matrices

Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be 1 x j  and column matrices would be i x 1

In [ ]:
## Declaring a Row Matrix

rowmatrix1D = np.array([
    10, 20, 30, -40
]) ## this is a 1-D Matrix with a shape of (4,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [2,4,6, -8]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)


Matrix:
[ 10  20  30 -40]

Shape:	(4,)
Rank:	1

Matrix:
[[ 2  4  6 -8]]

Shape:	(1, 4)
Rank:	2



In [ ]:
col_mat = np.array([
    [4],
    [6],
    [8]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)


Matrix:
[[4]
 [6]
 [8]]

Shape:	(3, 1)
Rank:	2



### Square Matrix

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [ ]:
square_mat = np.array([
    [6,2,4],
    [1,2,2],
    [9,4,5]
])

non_square_mat = np.array([
    [4,2,5],
    [6,8,7]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[6 2 4]
 [1 2 2]
 [9 4 5]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[4 2 5]
 [6 8 7]]

Shape:	(2, 3)
Rank:	2
Is Square: False



# According to element values

## Null Matrix

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')


In [ ]:
null_matrix = np.array([
    [6,2,4],
    [1,2,2],
    [9,4,5]
])
describe_mat(null_matrix)

## If we put 0 inside [], it will not be null anymore

Matrix:
[[6 2 4]
 [1 2 2]
 [9 4 5]]

Shape:	(3, 3)
Rank:	2
Is Square: True



## Zero Matrices

A zero matrix can be any rectangular matrix but with all elements having a value of 0

In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,3))
zero_mat_rct = np.zeros((4,3))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')


Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Ones Matrix

In [ ]:
ones_mat_row = np.ones((2,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((5,5))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


Ones Row Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Diagonal Matrix

there are values at the diagonal parts of the matrix

In [ ]:
np.array([
    [4,0,0,0],
    [0,8,0,0],
    [0,0,12,0],
    [0,0,0,16]

])

## Manually inputed diagonal matrix

array([[ 4,  0,  0,  0],
       [ 0,  8,  0,  0],
       [ 0,  0, 12,  0],
       [ 0,  0,  0, 16]])

In [ ]:
## Shortcut method
diag_matrix1 = np.diag([4,8,12,16])
diag_matrix2 = np.diag([2,4,6,8,10,12])

print(f'first matrix:\n {diag_matrix1}')
print(f'second matrix: \n {diag_matrix2}')

first matrix:
 [[ 4  0  0  0]
 [ 0  8  0  0]
 [ 0  0 12  0]
 [ 0  0  0 16]]
second matrix: 
 [[ 2  0  0  0  0  0]
 [ 0  4  0  0  0  0]
 [ 0  0  6  0  0  0]
 [ 0  0  0  8  0  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0  0 12]]


## Identity matrix
An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [ ]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.identity(6)


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Upper triangular Matrix
An upper triangular matrix is a matrix that has no values below the diagonal.

In [ ]:
## np.triu(T_matrix) will convert a normal matrix to an upper triangular matrix
T_matrix = np.array([
              
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
])
np.triu(T_matrix)



array([[ 2, -3,  4, -5,  6],
       [ 0, -3,  4, -5,  6],
       [ 0,  0,  4, -5,  6],
       [ 0,  0,  0, -5,  6],
       [ 0,  0,  0,  0,  6]])

## Lower Triangular Matrix

A lower triangular matrix is a matrix that has no values above the diagonal.

In [ ]:
np.tril(T_matrix)

array([[ 2,  0,  0,  0,  0],
       [ 2, -3,  0,  0,  0],
       [ 2, -3,  4,  0,  0],
       [ 2, -3,  4, -5,  0],
       [ 2, -3,  4, -5,  6]])

# **Practice**

1. *Given the linear combination below, try to create a corresponding matrix representing it*

:$$\theta = 5x + 3y - z$$


In [ ]:
practice1 = np.array([5,3,-1])

practice1

array([ 5,  3, -1])

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.
$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


In [3]:
## Creating a function
def m_describe(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

## Declaring matrix:
practice2 = np.array([
          (1,2,1),
          (4,-2,0),
          (10,0,0)
])

m_describe(practice2)

Matrix:
[[ 1  2  1]
 [ 4 -2  0]
 [10  0  0]]

Shape:	(3, 3)
Rank:	2



3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [5]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

G

array([[1, 7, 8],
       [2, 2, 2],
       [4, 6, 7]])

$$
A = \left\{\begin{array}
1x_3 + 7x_2 +8x\\
2x_3 + 2x_2 + 2x\\
4x_3 + 6x_2 + 7x
\end{array}\right.
$$

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [6]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

$$
A = \left\{\begin{array}
1x_3 \\
2x_3 + 2x_2 \\
4x_3 + 6x_2 + 7x
\end{array}\right.
$$

#Matrix Algebra

**ADDITION**

In [ ]:
A = np.array([
    [3,6],
    [9,12],
    [2,4]
])
B = np.array([
    [1,2],
    [3,0],
    [4,5]
])
A+B

array([[ 4,  8],
       [12, 12],
       [ 6,  9]])

In [ ]:
5+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[ 8, 11],
       [14, 17],
       [ 7,  9]])

**SUBTRACTION**

In [ ]:
A-B

array([[ 2,  4],
       [ 6, 12],
       [-2, -1]])

In [ ]:
6-B

array([[5, 4],
       [3, 6],
       [2, 1]])

**ELEMENT-WISE MULTIPLICATION**

In [ ]:
#You can use either A*B or np.multiply(A,B)

A*B

array([[ 3, 12],
       [27,  0],
       [ 8, 20]])

In [ ]:
3*B

array([[ 3,  6],
       [ 9,  0],
       [12, 15]])

In [ ]:
A@B

alpha=10**-10
A/(alpha+8)

In [ ]:
alpha=10**-10
A/(alpha+8)

array([[0.375, 0.75 ],
       [1.125, 1.5  ],
       [0.25 , 0.5  ]])

In [ ]:
np.add(A,B)

array([[ 4,  8],
       [12, 12],
       [ 6,  9]])

# Activity

## Task 1
Create a function named mat_desc() that througouhly describes a matrix, it should:

1. Displays the shape, size, and rank of the matrix.
2. Displays whether the matrix is square or non-square.
3. Displays whether the matrix is an empty matrix.
4. Displays if the matrix is an identity, ones, or zeros matrix


In [10]:
## Function Area
def mat_desc(mat):
    sq = False
    mat = np.array(mat)
    print(mat)
    print('Shape:', mat.shape)
    print('Size:', mat.size)
    print('Rank:', np.linalg.matrix_rank(mat))
    if(mat.shape[0] == mat.shape[1]):
        sq = True
        print('The matrix is square')
    else:
        print('The matrix is non-square')
    if(mat.shape[0] == 0 and mat.shape[1] == 0):
        print('The matrix is empty')
    else:
        print('The matrix is not empty')
    iden = np.identity(mat.shape[0])
    if(sq and (iden == mat).all()):
        print('The matrix is an identity matrix')
    else:
        print('The matrix is not an identity matrix')
    one = np.ones((mat.shape[0], mat.shape[1]))
    if((one == mat).all()):
        print('The matrix is an ones matrix')
    else:
        print('The matrix is not an ones matrix')
    zero = np.zeros((mat.shape[0], mat.shape[1]))
    if((zero == mat).all()):
        print('The matrix is an zeros matrix')
    else:
        print('The matrix is not a zeros matrix')



In [11]:
## Matrix Declaration
##matrix 1
mat_1 = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])
##matrix 2
mat_2 = np.ones((3,4))
##matrix 3
mat_3 = np.zeros((3,3))

In [12]:
## Test Areas
print('matrix 1:')
mat_desc(mat_1)
print('\nmatrix 2: ')
mat_desc(mat_2)
print('\nmatrix 3: ')
mat_desc(mat_3)

matrix 1:
[[1 2 5]
 [3 3 8]
 [6 1 2]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix

matrix 2: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape: (3, 4)
Size: 12
Rank: 1
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is an ones matrix
The matrix is not a zeros matrix

matrix 3: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape: (3, 3)
Size: 9
Rank: 0
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is an zeros matrix


##Task 2
Create a function named mat_operations() that takes in two matrices a input parameters it should:

1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
2. Returns the sum of the matrices.
3. Returns the differen of the matrices.
4. Returns the element-wise multiplication of the matrices
5. Returns the element-wise division of the matrices.


In [13]:
def mat_operations(matrix):
  print (f'{matrix}')

In [14]:
## Matrix 1
row1 = int(input("enter the row number of the first matrix: " ))
col1 = int(input("enter the column number of the first matrix: "))

print('enter', row1*col1, 'elements for matrix 1: ')
matrix1 = list(map(int, input().split()))
r_matrix1 = np.array(matrix1).reshape(row1,col1)
print("matrix 1 is: ")
mat_operations(r_matrix1)

## Matrix 2
row2 = int(input("\nenter the row number of the second matrix: " ))
col2 = int(input("enter the column number of the second matrix: "))

print('enter', row2*col2, 'elements for matrix 2: ')
matrix2 = list(map(int, input().split()))
r_matrix2 = np.array(matrix2).reshape(row2,col2)
print("matrix 2 is: ")
mat_operations(r_matrix2)

## Matrix 3
row3 = int(input("\nenter the row number of the third matrix: " ))
col3 = int(input("enter the column number of the third matrix: "))

print('enter', row3*col3, 'elements for matrix 3: ')
matrix3 = list(map(int, input().split()))
r_matrix3 = np.array(matrix3).reshape(row3,col3)
print("matrix 3 is: ")
mat_operations(r_matrix3)

first = r_matrix1
second = r_matrix2
third = r_matrix3
### ADDITION ----------------------------------------------------------------
print('\nselect two matrices to to add. (Note: use first, second, third, to select the matrices)')
firstadd = str(input("matrix #: "))
print('+') 
secondadd =str(input("matrix #: "))

result = (eval(firstadd).shape == eval(secondadd).shape)
if result:
  print('\nThe sum of the',firstadd,'and',secondadd,'matrix is: ')
  print(eval(firstadd)+eval(secondadd))
else:
  print('\nOperation not viable, check matrix dimensions.') 

###SUBTRACTION--------------------------------------------------------------
print('\nselect two matrices to to subtract')
firstsubb = str(input("matrix #: ")) 
print('-') 
secondsubb =str(input("matrix #: "))

result = (eval(firstsubb).shape == eval(secondsubb).shape)
if result:
  print('\nThe difference of the',firstsubb,'and',secondsubb,'matrix is: ')
  print(eval(firstsubb)-eval(secondsubb))
else:
  print('\nOperation not viable, check matrix dimensions.') 

###ELEMENT-WISE MULTIPLICATION----------------------------------------------
print('\nselect two matrices to multiply')
firstmult = str(input("matrix #: "))
print('x') 
secondmult =str(input("matrix #: "))

result = (eval(firstmult).shape == eval(secondmult).shape)
if result:
  print('\nThe product of the',firstmult,'and',secondmult,'matrix is: ')
  print(eval(firstmult)*eval(secondmult))
else:
  print('\nOperation not viable, check matrix dimensions.') 

### ELEMENT-WISE DIVISION --------------------------------------------------
print('\nselect two matrices to divide')
firstdiv = str(input("matrix #: "))
print('/')
seconddiv =str(input("matrix #: "))

result = (eval(firstdiv).shape == eval(seconddiv).shape)
if result:
  print('\nThe product of the',firstdiv,'and',seconddiv,'matrix is: ')
  print(eval(firstdiv)/eval(seconddiv))
else: 
  print('\nOperation not viable, check matrix dimensions.') 

enter the row number of the first matrix: 3
enter the column number of the first matrix: 4
enter 12 elements for matrix 1: 
2 3 4 1 2 4 5 3 4 7 2 3
matrix 1 is: 
[[2 3 4 1]
 [2 4 5 3]
 [4 7 2 3]]

enter the row number of the second matrix: 3
enter the column number of the second matrix: 4
enter 12 elements for matrix 2: 
2 3 1 4 5 2 2 2 2 3 3 4
matrix 2 is: 
[[2 3 1 4]
 [5 2 2 2]
 [2 3 3 4]]

enter the row number of the third matrix: 3
enter the column number of the third matrix: 3
enter 9 elements for matrix 3: 
2 3 1 1 4 1 1 4 1
matrix 3 is: 
[[2 3 1]
 [1 4 1]
 [1 4 1]]

select two matrices to to add. (Note: use first, second, third, to select the matrices)
matrix #: first
+
matrix #: second

The sum of the first and second matrix is: 
[[ 4  6  5  5]
 [ 7  6  7  5]
 [ 6 10  5  7]]

select two matrices to to subtract
matrix #: first
-
matrix #: third

Operation not viable, check matrix dimensions.

select two matrices to multiply
matrix #: first
x
matrix #: second

The product of the 